# -*- coding: utf-8 -*-
"""Continuando com Collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S-UbYURiOI7FBYmndXxYZNociLWyWWfP
"""

usuarios_data_science = [15, 23, 43, 56]
usuarios_machine_learning = [13, 23, 56, 42]

#Faz uma copia referenciando os mesmos objetos que sao inteiros
assistiram = usuarios_data_science.copy()

#Concatena 2 listas
assistiram.extend(usuarios_machine_learning)
assistiram

len(assistiram)


#Set sao conjuntos que igual na matematica e que por padrao removem 
#Tipos duplicados
set(assistiram)

set([1,2,3,1])

{4, 1,2,3,1}

type({1,2})

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

usuarios_machine_learning

#Isso vai dar erro pq e um conjunto e nao possui posicao
usuarios_machine_learning[3]

#Mas voce consegue interar
for usuario in set(assistiram):
  print(usuario)

usuarios_data_science = {15, 23, 43, 56}
usuarios_machine_learning = {13, 23, 56, 42}

# Operacao de OU
usuarios_data_science | usuarios_machine_learning

#Operacao de AND
usuarios_data_science & usuarios_machine_learning

usuarios_data_science - usuarios_machine_learning


fez_ds_mas_nao_fez_ml = usuarios_data_science - usuarios_machine_learning

#Verifica se esta no conjunto
15 in fez_ds_mas_nao_fez_ml

23 in fez_ds_mas_nao_fez_ml

#
usuarios_data_science ^ usuarios_machine_learning



