#Inseting ROWS
cat > /home/oracle/insertrows.sql <<EOF 
BEGIN 
 FOR I IN 1..&1 LOOP  
  INSERT INTO TEST_TABLE ( RNAME ) VALUES (DBMS_RANDOM.STRING('U', 10)); 
 END LOOP; 
 COMMIT; 
END; 
/ 
EOF



-- View tablespace of the TABLE
SELECT TABLESPACE_NAME FROM USER_TABLES WHERE TABLE_NAME='TEST_TABLE'; 

#View if omf is ENabled
show parameter DB_CREATE_FILE_DEST

#Create a TABLESPACE
SELECT EXTENT_MANAGEMENT, SEGMENT_SPACE_MANAGEMENT 
FROM DBA_TABLESPACES 
WHERE TABLESPACE_NAME='HRTBS'; 

#Check the datafile name created for the tablespace. 
SELECT FILE_NAME FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='USERS';

#Retrieve the permanent and temporary tablespaces in the entire database. 
col pdb_name format a10 
 
SELECT T.TABLESPACE_NAME, T.CON_ID, P. PDB_NAME 
FROM   CDB_TABLESPACES T, CDB_PDBS P 
WHERE  T.CON_ID = P.CON_ID (+) 
ORDER BY 2,1; 


#View the size of the tablespaces in the entire database
set linesize 180 
col CON_ID for 99 
col TABLESPACE_NAME for A15 
col "Free %" for A8 
 
SELECT F.CON_ID  
      ,F.TABLESPACE_NAME 
      ,F.TOTALSPACE "Size MB" 
      ,(F.TOTALSPACE - U.TOTALUSEDSPACE) "Free MB" 
      ,ROUND (100 * ( (F.TOTALSPACE - U.TOTALUSEDSPACE) / F.TOTALSPACE)) || '%' 
"Free %" 
      ,T.MAX_S "Max Size" 
FROM   (SELECT   CON_ID, TABLESPACE_NAME, ROUND (SUM (BYTES) / (1024 * 1024)) 
TOTALSPACE 
        FROM     CDB_DATA_FILES 
        GROUP BY CON_ID, TABLESPACE_NAME) F 
      ,(SELECT   CON_ID, TABLESPACE_NAME, ROUND (SUM (BYTES) / (1024 * 1024)) 
TOTALUSEDSPACE 
        FROM     CDB_SEGMENTS 
        GROUP BY CON_ID, TABLESPACE_NAME) U 
      ,(SELECT CON_ID, TABLESPACE_NAME, ROUND (MAX_SIZE / (1024 * 1024)) MAX_S  
        FROM     CDB_TABLESPACES        ) T 
WHERE  (F.TABLESPACE_NAME = U.TABLESPACE_NAME AND F.CON_ID= U.CON_ID) 
  AND  (F.TABLESPACE_NAME = T.TABLESPACE_NAME AND F.CON_ID = T.CON_ID) 
ORDER BY CON_ID ; 



#View tablespace of PDB only
ALTER SESSION SET CONTAINER=PDB; 

SELECT F.TABLESPACE_NAME 
      ,F.TOTALSPACE "Size MB" 
      , (F.TOTALSPACE - U.TOTALUSEDSPACE) "Free MB" 
      ,ROUND (100 * ( (F.TOTALSPACE - U.TOTALUSEDSPACE) / F.TOTALSPACE)) || '%' 
"Free %" 
      ,T.MAX_S "Max Size" 
FROM   (SELECT   TABLESPACE_NAME, ROUND (SUM (BYTES) / (1024 * 1024)) TOTALSPACE 
        FROM     DBA_DATA_FILES 
        GROUP BY TABLESPACE_NAME) F 
      ,(SELECT   TABLESPACE_NAME, ROUND (SUM (BYTES) / (1024 * 1024)) 
TOTALUSEDSPACE 
        FROM     DBA_SEGMENTS 
        GROUP BY TABLESPACE_NAME) U 
      ,( SELECT TABLESPACE_NAME, ROUND (MAX_SIZE / (1024 * 1024)) MAX_S  
        FROM     DBA_TABLESPACES) T 
WHERE  F.TABLESPACE_NAME = U.TABLESPACE_NAME(+)  
  AND  F.TABLESPACE_NAME = T.TABLESPACE_NAME;



CREATE PLUGGABLE DATABASE swingbench
ADMIN USER swingbench_admin IDENTIFIED BY ABcd##1234
DEFAULT TABLESPACE my_pdb_ts
DATAFILE SIZE 100M AUTOEXTEND ON NEXT 10M;


CREATE PLUGGABLE DATABASE hr
ADMIN USER hr_admin IDENTIFIED BY ABcd##1234
DEFAULT TABLESPACE hr_pdb_ts
DATAFILE SIZE 100M AUTOEXTEND ON NEXT 10M;

ALTER SESSION SET CONTAINER=hr