-- start with HR_OFFICER_ROLE -- grant the required system privileges 
GRANT CREATE SESSION, CREATE SYNONYM TO HR_OFFICER_ROLE; 
 -- grant the required object privileges to the role: 
GRANT SELECT, INSERT, UPDATE ON HR.REGIONS TO HR_OFFICER_ROLE; 
GRANT SELECT, INSERT, UPDATE ON HR.COUNTRIES TO HR_OFFICER_ROLE; 
GRANT SELECT, INSERT, UPDATE ON HR.LOCATIONS TO HR_OFFICER_ROLE; 
GRANT SELECT, INSERT, UPDATE ON HR.DEPARTMENTS TO HR_OFFICER_ROLE; 
GRANT SELECT, INSERT, UPDATE ON HR.JOBS TO HR_OFFICER_ROLE; 
GRANT SELECT, INSERT, UPDATE ON HR.EMPLOYEES TO HR_OFFICER_ROLE; 
GRANT SELECT, INSERT, UPDATE ON HR.JOB_HISTORY TO HR_OFFICER_ROLE; 
 -- now for HR_REPORTER_ROLE -- grant the required system privileges 
GRANT CREATE SESSION, CREATE SYNONYM TO HR_REPORTER_ROLE; 
 -- grant the required object privileges to the role: 
GRANT READ ON HR.REGIONS TO HR_REPORTER_ROLE; 
GRANT READ ON HR.COUNTRIES TO HR_REPORTER_ROLE; 
GRANT READ ON HR.LOCATIONS TO HR_REPORTER_ROLE; 
GRANT READ ON HR.DEPARTMENTS TO HR_REPORTER_ROLE; 
GRANT READ ON HR.JOBS TO HR_REPORTER_ROLE; 
GRANT READ ON HR.EMPLOYEES TO HR_REPORTER_ROLE; 
GRANT READ ON HR.JOB_HISTORY TO HR_REPORTER_ROLE; 


-- Verify that the privileges are assigned to the roles.
col GRANTEE for a20 
SELECT GRANTEE , PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE IN 
('HR_OFFICER_ROLE', 'HR_REPORTER_ROLE') 
ORDER BY 1,2; 
 
SELECT GRANTEE , PRIVILEGE FROM DBA_TAB_PRIVS WHERE GRANTEE IN 
('HR_OFFICER_ROLE', 'HR_REPORTER_ROLE') 
ORDER BY 1,2;

-- Grant Roles to the users
GRANT HR_OFFICER_ROLE TO HR_OFFICER; 
GRANT HR_REPORTER_ROLE TO HR_REPORTER; 

-- Verify if is applied to the users
col GRANTED_ROLE for a20 
SELECT GRANTEE , GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE IN 
('HR_OFFICER', 'HR_REPORTER') 
ORDER BY 1,2; 